import { Teacher, Facility, Achievement, GalleryItem, DownloadItem, CommitteeMember, MenuItem, RegistrationData } from './types';

export const MENU_ITEMS: MenuItem[] = [
  { id: 'home', label: 'Beranda', category: 'main', iconName: 'Home' },
  { id: 'profile', label: 'Profil Sekolah', category: 'school', iconName: 'School' },
  { id: 'spmb-info', label: 'Informasi SPMB', category: 'spmb', iconName: 'Info' },
  { id: 'annual-fees', label: 'Biaya Tahunan', category: 'spmb', iconName: 'CreditCard' },
  { id: 'schedule', label: 'Jadwal Pendaftaran', category: 'spmb', iconName: 'Calendar' },
  { id: 'requirements', label: 'Persyaratan Daftar', category: 'spmb', iconName: 'CheckSquare' },
  { id: 'procedure', label: 'Alur Pendaftaran', category: 'spmb', iconName: 'GitFork' },
  { id: 'teachers', label: 'Guru & Staf', category: 'school', iconName: 'Users' },
  { id: 'facilities', label: 'Fasilitas Sekolah', category: 'school', iconName: 'Building2' },
  { id: 'achievements', label: 'Prestasi', category: 'school', iconName: 'Trophy' },
  { id: 'gallery', label: 'Agenda Kegiatan', category: 'school', iconName: 'Calendar' },
  { id: 'downloads', label: 'Unduhan Dokumen', category: 'spmb', iconName: 'FileDown' },
  { id: 'committee', label: 'Panitia SPMB', category: 'spmb', iconName: 'UserCheck' },
  { id: 'contact', label: 'Hubungi Kami', category: 'main', iconName: 'Phone' },
  { id: 'registration-form', label: 'Formulir Pendaftaran', category: 'action', iconName: 'FileEdit' },
  { id: 'registration-status', label: 'Cek Status Kelulusan', category: 'action', iconName: 'Search' },
];

export const TEACHERS: Teacher[] = [
  // Kepemimpinan
  {
    id: 't1',
    name: 'Pankrasius Rasmani, S.Pd.',
    role: 'Kepala Sekolah',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'kepemimpinan',
  },
  {
    id: 't2',
    name: 'Ignas Lehan, S.Pd.',
    role: 'WAKASEK Kurikulum',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'kepemimpinan',
  },
  {
    id: 't3',
    name: 'Yeremias Dhai, S.Pd.',
    role: 'WAKASEK Sarpras',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'kepemimpinan',
  },
  {
    id: 't4',
    name: 'Aurelia Dorce, S.Pd.',
    role: 'WAKASEK Humas',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'kepemimpinan',
  },
  {
    id: 't5',
    name: 'Abdul Manan, S.Pd.',
    role: 'Perpustakaan',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'kepemimpinan',
  },
  {
    id: 't6',
    name: 'Nestliante Admini, S.Pd.',
    role: 'Laboratorium',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'kepemimpinan',
  },

  // Dewan Guru
  {
    id: 't7',
    name: 'Felixitus, S.Pd.',
    role: 'Guru PJOK',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'guru',
  },
  {
    id: 't8',
    name: 'Yohanes Aster Wongga, S.Pd.',
    role: 'Guru PJOK',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'guru',
  },
  {
    id: 't9',
    name: 'Fransiskus France, S.Pd.',
    role: 'Guru Matematika',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'guru',
  },
  {
    id: 't10',
    name: 'Umiyani, S.Pd.',
    role: 'Guru Bahasa Indonesia',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'guru',
  },
  {
    id: 't11',
    name: 'Januarius Bartolomeus Carvallo, S.Ag.',
    role: 'Guru Agama Katolik',
    photoUrl: '',
    education: 'S1 Pendidikan Agama',
    category: 'guru',
  },
  {
    id: 't12',
    name: 'Emanuel P. Molan, S.Ag.',
    role: 'Guru Agama Katolik',
    photoUrl: '',
    education: 'S1 Pendidikan Agama',
    category: 'guru',
  },

  // Tenaga Staf
  {
    id: 't13',
    name: 'Yohanes Aster Wongga, S.Pd.',
    role: 'Kepala Tata Usaha',
    photoUrl: '',
    education: 'S1 Kependidikan',
    category: 'staf',
  },
  {
    id: 't14',
    name: 'Januarius Bartolomeus Carvallo, S.Ag.',
    role: 'Operator Dapodik',
    photoUrl: '',
    education: 'S1 Pendidikan Agama',
    category: 'staf',
  },
];

export const FACILITIES: Facility[] = [
  {
    id: 'f1',
    name: 'Ruang Komputer',
    description: 'Ruang lab computer, terkoneksi internet Bhakti Aksi untuk kenyamanan Pembelajaran Informatika dan asesmen nasional (ANBK) dan TKA.',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=600&h=400',
    iconName: 'Laptop',
  },
  {
    id: 'f2',
    name: 'Perpustakaan fisik dan Online "Cahaya Ilmu"',
    description: 'Menyediakan ribuan koleksi buku pelajaran, fiksi, referensi ilmiah, serta sudut baca digital mandiri yang nyaman bagi siswa mengeksplorasi wawasan.',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&q=80&w=600&h=400',
    iconName: 'BookOpen',
  },
  {
    id: 'f3',
    name: 'Laboratorium IPA Terpadu',
    description: 'Fasilitas praktikum Fisika, Kimia, dan Biologi dengan mikroskop digital, torso anatomi, alat peraga sains lengkap, dan standar keselamatan kerja yang tinggi.',
    imageUrl: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&q=80&w=600&h=400',
    iconName: 'Beaker',
  },
  {
    id: 'f4',
    name: 'Lapangan Terbuka',
    description: 'Lapangan terbuka yang representatif untuk kegiatan upacara bendera, serta olahraga basket, voli, futsal, dan latihan keahlian atletik siswa.',
    imageUrl: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?auto=format&fit=crop&q=80&w=600&h=400',
    iconName: 'Activity',
  },
  {
    id: 'f5',
    name: 'Kantin Sekolah',
    description: 'Kantin ramah lingkungan yang menyediakan makanan berstandar higienis.',
    imageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&q=80&w=600&h=400',
    iconName: 'Utensils',
  },
  {
    id: 'f6',
    name: 'Alat Musik Tradisional',
    description: 'Alat musik tradisional super lengkap seperti Gong Waning untuk menyegarkan kecintaan nilai adat luhur di kalangan tunas bangsa serta mengiringi berbagai pentas tarian daerah.',
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&q=80&w=600&h=400',
    iconName: 'Music',
  },
  {
    id: 'f7',
    name: 'Peralatan Tenun Ikat Tradisional',
    description: 'Sarana kreasi tenun ikat adat Sikka yang lengkap, merajut untaian benang keindahan nusantara sekaligus menumbuhkan kecakapan wirausaha budaya mandiri.',
    imageUrl: 'https://images.unsplash.com/photo-1584905066893-7d5c142ba4e1?auto=format&fit=crop&q=80&w=600&h=400',
    iconName: 'Palette',
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'a1',
    title: 'Juara IV Lomba Gerak jalan Tingkat Kabupaten',
    level: 'Kabupaten',
    year: '2024',
    category: 'Akademik',
    recipient: 'Tim Cerdas Cermat SMPN 2 Waigete',
    description: 'Berjuang dengan kerukunan derap langkah yang serasi dan keselarasan baris tinggi, delegasi kami berhasil membuktikan dedikasi penuh ketangkasan di tingkat Kabupaten Sikka.',
  },
  {
    id: 'a2',
    title: 'Peringkat 3 tournamen volley antar SMP',
    level: 'Kabupaten',
    year: '2026',
    category: 'Non-Akademik',
    recipient: 'Tim Voli SMPN 2 Waigete',
    description: 'Berkat smash yang tajam, kerja sama tim yang solid rukun, serta pertahanan kokoh tak tergoyahkan, para atlet berbakat kami membawa pulang trofi perunggu kebanggaan.',
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'g1',
    title: 'Kegiatan Pembelajaran Berbasis Proyek (P5)',
    category: 'KBM',
    imageUrl: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&q=80&w=600&h=400',
    description: 'Siswa kelas VII memamerkan hasil anyaman bambu khas NTT dalam proyek penguatan profil pelajar pancasila.',
  },
  {
    id: 'g2',
    title: 'Latihan Pramuka Ekstrakurikuler Wajib',
    category: 'Ekstrakurikuler',
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=600&h=400',
    description: 'Latihan tali temali dan pembentukan karakter kepemudaan di lapangan utama setiap hari Jumat sore.',
  },
  {
    id: 'g3',
    title: 'Upacara Bendera Hari Guru Nasional',
    category: 'Acara',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=600&h=400',
    description: 'Upacara khidmat yang dipimpin langsung oleh Bapak Pankrasius Rasmani selaku Pembina Upacara.',
  },
  {
    id: 'g4',
    title: 'Praktikum Anatomi di Laboratorium IPA Terpadu',
    category: 'KBM',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=600&h=400',
    description: 'Siswa antusias mempelajari organ tubuh menggunakan model torso interaktif didampingi guru mapel.',
  },
  {
    id: 'g5',
    title: 'Pesta Paduan Suara Sekolah di Gereja Waigete',
    category: 'Ekstrakurikuler',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=600&h=400',
    description: 'Harmonisasi suara merdu generasi muda Waigete menyanyikan puji-pujian rohani dan lagu kebangsaan.',
  },
  {
    id: 'g20',
    title: 'Laboratorium Komputer Asesmen Nasional',
    category: 'Fasilitas',
    imageUrl: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&q=80&w=600&h=400',
    description: 'Penyelenggaraan gladi bersih ANBK mandiri yang diikuti seluruh siswa tingkat akhir dengan lancar.',
  },
];

export const DOWNLOAD_ITEMS: DownloadItem[] = [
  {
    id: 'd1',
    title: 'Brosur Resmi Penerimaan Murid Baru (SPMB) 2026/2027',
    description: 'Brosur lengkap yang berisi profil sekolah, syarat administrasi, rincian biaya (gratis/subsidi pemerintah), dan narahubung.',
    fileSize: '2.4 MB',
    fileType: 'PDF',
    downloadUrl: '#',
  },
  {
    id: 'd2',
    title: 'Formulir Pendaftaran Siswa Baru - Jalur Offline',
    description: 'Formulir cetak resmi bagi orang tua yang ingin mengumpulkan berkas secara langsung ke sekretariat SPMB sekolah.',
    fileSize: '340 KB',
    fileType: 'PDF',
    downloadUrl: '#',
  },
  {
    id: 'd3',
    title: 'Surat Pernyataan Orang Tua / Wali Siswa',
    description: 'Dokumen pernyataan kesetiaan mengikuti tata tertib sekolah dan mendukung program komite sekolah (bermaterai 10.000).',
    fileSize: '120 KB',
    fileType: 'DOCX',
    downloadUrl: '#',
  },
  {
    id: 'd4',
    title: 'Panduan Teknis Verifikasi Berkas Online',
    description: 'Panduan lengkap langkah demi langkah bagi pendaftar online untuk mengunggah dokumen akta kelahiran, KK, dan SKL SD.',
    fileSize: '1.1 MB',
    fileType: 'PDF',
    downloadUrl: '#',
  },
];

export const COMMITTEE_MEMBERS: CommitteeMember[] = [
  {
    id: 'c1',
    name: 'Pankrasius Rasmani, S.Pd',
    role: 'Kepala Sekolah / Penanggung Jawab',
    phone: '+62 823-4178-9194',
    section: 'Penanggung Jawab & Pelindung Kegiatan SPMB',
  },
  {
    id: 'c2',
    name: 'Umiyani, S.Pd',
    role: 'Ketua Panitia SPMB 2026-2027',
    phone: '+62 812-3714-3514',
    section: 'Ketua Koordinator Pelaksana Kebijakan & Teknis',
  },
  {
    id: 'c3',
    name: 'Januarius B. Carvallo, S.Ag',
    role: 'Sekretaris SPMB 2026-2027',
    phone: '+62 812-3780-6460',
    section: 'Sekretaris Pelaksana, Administrasi & Operator Data (Pak Yano)',
  },
  {
    id: 'c4',
    name: 'Anastasya Tatty Kewa Somi, S.Pd',
    role: 'Bendahara SPMB 2026-2027',
    phone: '+62 812-3645-1768',
    section: 'Bendahara Pelaksana, Keuangan & Logistik Berkas',
  },
  {
    id: 'c5',
    name: 'Guru dan Pegawai SMPN 2 Waigete',
    role: 'Anggota Panitia SPMB 2026-2027',
    phone: '',
    section: 'Anggota Pelaksana Lapangan, Konsultasi & Verifikasi Fisik',
  },
];

// Initial pre-registrations for demo search lookup
export const DEMO_REGISTRATIONS: RegistrationData[] = [
  {
    id: 'REG-2026-001',
    nisn: '0123456789',
    fullName: 'Yohanes Kristian da Silva',
    gender: 'Laki-laki',
    birthPlace: 'Waigete, Sikka',
    birthDate: '2014-04-12',
    previousSchool: 'SDN Sikka 2',
    parentName: 'Marcus da Silva',
    parentPhone: '081233445566',
    parentAddress: 'Desa Runut, Sikka, NTT',
    status: 'Diterima',
    submittedAt: '2026-06-01T08:30:00Z',
    notes: 'Selamat! Berkas Anda dinyatakan lengkap dan dinyatakan LULUS seleksi berkas. Silakan melakukan pendaftaran ulang di sekolah pada tanggal 7 - 10 Juli 2026.',
  },
  {
    id: 'REG-2026-002',
    nisn: '0112233445',
    fullName: 'Maria Goreti Boleng',
    gender: 'Perempuan',
    birthPlace: 'Maumere',
    birthDate: '2013-11-20',
    previousSchool: 'SD Inpres Waigete',
    parentName: 'Ignatius Boleng',
    parentPhone: '081344455566',
    parentAddress: 'Dusun Habi Gete, Waigete',
    status: 'Terverifikasi',
    submittedAt: '2026-06-01T09:15:00Z',
    notes: 'Berkas fisik dan digital Anda telah diverifikasi oleh Pak Yoseph Keytimu. Menunggu rapat pleno pengumuman pada 5 Juli 2026.',
  },
  {
    id: 'REG-2026-003',
    nisn: '0144556677',
    fullName: 'Ahmad Faisal Mubarak',
    gender: 'Laki-laki',
    birthPlace: 'Ende',
    birthDate: '2014-01-05',
    previousSchool: 'SD Muhammadiyah Maumere',
    parentName: 'Sulaeman Mubarak',
    parentPhone: '082155566677',
    parentAddress: 'Jl. Trans Maumere-Larantuka, Waigete',
    status: 'Pending',
    submittedAt: '2026-06-01T09:45:00Z',
    notes: 'Pendaftaran diterima secara online. Silakan lengkapi berkas foto pas 3x4 berwarna ke loket panitia atau unggah dalam bentuk PDF.',
  },
];
